---
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: "blackbox-exporter-rules"
    namespace: "default" # release
    createNamespace: false
    chart: "./blackbox-exporter-rules"
    values:
      - probes:
          - name: google
            targets:
              - https://www.google.com
          - name: openshift-components
            targets:
              - https://api.cluster.example.com:6443
              - https://console-openshift-console.cluster.example.com

  - name: "blackbox-exporter"
    namespace: "blackbox-exporter"
    createNamespace: false
    chart: "prometheus-community/prometheus-blackbox-exporter"
    values:
      - fullnameOverride: blackbox-exporter
        runAsUser: ""
        pspEnabled: false
        replicas: 2
